# PenomatiK general configs
#

## Site settings
title: YOUR BLOG TITLE
description: YOUR BLOG DESCRIPTIONS

author: YOUR NAME
email: your-email@domain.com

# each field you make here, like twitter and...
# is available in template: {{ SITE.twitter }}
twitter: https://www.twitter.com/Your_Twitter_NAME


 # the base hostname & protocol for your site
url: http://localhost:80/blog
root: /blog/
# if fill static and imageurl, they will be cretaed in your root
# change from /MAIN_ROOT/YOUR_MAIN_STATIC_PATH to-> /MAIN_ROOT/FLOOR_ROOT/YOUR_STATIC_PATH
# and
# change from /MAIN_ROOT/YOUR_MAIN_Image_PATH to-> /MAIN_ROOT/FLOOR_ROOT/YOUR_Image_PATH
# static: /static
# imageurl: /static/img

## default post permanent link
permalink: :year/:month/:day/:title/

##date format default is gregorian, but you can change it to jalali
#date_format: jalali

## Your local Time Zone
TimeZone: +00:00

## Build settings
default_markup: markdown

## number of posts will be show in main index page
post_num: 5

## number of posts will be show in archives index page
archive_post_num: 20

## template path by root is penurlPATH/template
## if you want use a custom template for examle in penurlPATH/template/CustomThEM
## just type custom template folder name
#> template: Custom_Template_Folde_Name
template: mira-theme

## the fields you want use for archive, like category, tag and ...
## by default Mira archive date field dont need type it here
## Mira use this fields by default for the floors which haven't field section
## in FloorName.yaml, or haven't FloorName.yaml file

#this fields are not allowed: archives, static
lists:
 - date
 - categories
 - tags

## your field archive hmtl addresses which you want change
namespace:
  veryveryveryLongFieldName: lfn
  learning posts: learn
  درباره: about
  شخصی: personal


social:
 -  icon: twitter
    url: https://twitter.com/Twitter_UserName
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

 -  icon: github
    url: https://github.com/GitHub_UserName
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

 -  icon: instagram
    url: https://instagram.com/NAME
    desc: Follow me
    share_url:
    share_title:
    share_link:
